### ISSUE TITLE
怎么卸载

### ISSUE THREAD

**Issue by RedTeamExp** [veo/vbackdoor#1]
尝试使用echo "" > /etc/ld.so.preload 无效

**Comment by veo** [comment]
> 尝试使用echo "" > /etc/ld.so.preload 无效

echo  > /etc/ld.so.preload
还不行的话用busybox删除

**Comment by RedTeamExp** [comment]
vim /etc/ld.so.preload 修改就行

**Comment by veo** [comment]
> vim /etc/ld.so.preload 修改就行

嗯，可以的
