### ISSUE TITLE
无法隐藏tcp udp 网络连接 望更新

### ISSUE THREAD

**Issue by xiaojj2021** [veo/vbackdoor#7]
无法隐藏tcp udp 网络连接 望更新

**Comment by veo** [comment]
这个技术落后了，不会再更新了

**Comment by xiaojj2021** [comment]
还有啥用的吗 ，vshell提个小意见，每次输完命令会在/tmp/.del  ，建议关闭终端的时候删除这文件

**Comment by veo** [comment]
> 还有啥用的吗 ，vshell提个小意见，每次输完命令会在/tmp/.del ，建议关闭终端的时候删除这文件

为了存储历史命令一定会保留，历史命令总需要一个载体。实在不想留，可以在关闭后在文件管理内删除这个文件。
